-- ============================================================
-- ============================================================
-- SISTEMA DE SEGUIMIENTO A GRADUADOS
-- Carrera: Ingeniería Informática
-- Base de datos: PostgreSQL / Supabase
-- ============================================================
-- VERSIÓN CORREGIDA
-- ============================================================


-- ============================================================
-- 1. EXTENSIONES
-- ============================================================

create extension if not exists "uuid-ossp";


-- ============================================================
-- 2. ROLES
-- ============================================================

create table public.roles (
    id bigint generated by default as identity primary key,

    nombre varchar(30) not null unique,

    descripcion varchar(200),

    created_at timestamptz not null default now()
);


-- ============================================================
-- 3. PERFILES / USUARIOS
-- Vinculados con auth.users de Supabase
-- ============================================================

create table public.perfiles (

    id uuid primary key
        references auth.users(id)
        on delete cascade,

    id_rol bigint not null
        references public.roles(id)
        on delete restrict,

    nombres varchar(100) not null,

    apellidos varchar(100) not null,

    telefono varchar(30),

    estado boolean not null default true,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);


-- ============================================================
-- 4. GRADUADOS
-- Información específica del graduado
-- ============================================================

create table public.graduados (

    id uuid primary key
        references public.perfiles(id)
        on delete cascade,

    ci varchar(30) unique,

    fecha_nacimiento date,

    año_ingreso integer,

    año_egreso integer,

    año_titulacion integer,

    modalidad_titulacion varchar(100),

    ciudad varchar(100),

    departamento varchar(100),

    direccion varchar(255),

    linkedin varchar(255),

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint chk_año_ingreso
        check (
            año_ingreso is null
            or año_ingreso >= 1900
        ),

    constraint chk_año_egreso
        check (
            año_egreso is null
            or año_egreso >= 1900
        ),

    constraint chk_año_titulacion
        check (
            año_titulacion is null
            or año_titulacion >= 1900
        ),

    constraint chk_años_graduado
        check (
            (
                año_ingreso is null
                or año_egreso is null
                or año_egreso >= año_ingreso
            )
            and
            (
                año_egreso is null
                or año_titulacion is null
                or año_titulacion >= año_egreso
            )
        )
);


-- ============================================================
-- 5. ENCUESTAS
-- ============================================================

create table public.encuestas (

    id uuid primary key
        default gen_random_uuid(),

    titulo varchar(200) not null,

    descripcion text,

    fecha_inicio date,

    fecha_fin date,

    estado boolean not null default false,

    id_usuario_creador uuid
        references public.perfiles(id)
        on delete set null,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint chk_fechas_encuesta
        check (
            fecha_fin is null
            or fecha_inicio is null
            or fecha_fin >= fecha_inicio
        )
);


-- ============================================================
-- 6. PREGUNTAS
-- ============================================================

create table public.preguntas (

    id uuid primary key
        default gen_random_uuid(),

    id_encuesta uuid not null
        references public.encuestas(id)
        on delete cascade,

    pregunta text not null,

    tipo varchar(30) not null,

    obligatoria boolean not null default false,

    orden integer not null default 1,

    valor_minimo integer,

    valor_maximo integer,

    etiqueta_minimo varchar(100),

    etiqueta_maximo varchar(100),

    created_at timestamptz not null default now(),

    constraint chk_tipo_pregunta
        check (
            tipo in (
                'TEXTO',
                'TEXTAREA',
                'NUMERO',
                'RADIO',
                'CHECKBOX',
                'SELECT',
                'ESCALA',
                'FECHA'
            )
        ),

    constraint chk_orden_pregunta
        check (
            orden > 0
        ),

    constraint chk_escala
        check (
            tipo <> 'ESCALA'
            or (
                valor_minimo is not null
                and valor_maximo is not null
                and valor_maximo > valor_minimo
            )
        )
);


-- ============================================================
-- 7. OPCIONES DE PREGUNTAS
-- RADIO, CHECKBOX y SELECT
-- ============================================================

create table public.opciones_pregunta (

    id uuid primary key
        default gen_random_uuid(),

    id_pregunta uuid not null
        references public.preguntas(id)
        on delete cascade,

    opcion varchar(255) not null,

    orden integer not null default 1,

    created_at timestamptz not null default now(),

    constraint chk_orden_opcion
        check (
            orden > 0
        )
);


-- ============================================================
-- 8. RESPUESTAS DE UNA ENCUESTA
-- Representa el envío completo de una encuesta
-- ============================================================

create table public.respuestas_encuesta (

    id uuid primary key
        default gen_random_uuid(),

    id_encuesta uuid not null
        references public.encuestas(id)
        on delete cascade,

    id_graduado uuid not null
        references public.graduados(id)
        on delete cascade,

    fecha_respuesta timestamptz not null default now(),

    estado varchar(20) not null default 'BORRADOR',

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint chk_estado_respuesta
        check (
            estado in (
                'BORRADOR',
                'COMPLETADA'
            )
        ),

    constraint uq_graduado_encuesta
        unique (
            id_encuesta,
            id_graduado
        )
);


-- ============================================================
-- 9. RESPUESTAS DETALLADAS
-- ============================================================

create table public.respuestas (

    id uuid primary key
        default gen_random_uuid(),

    id_respuesta_encuesta uuid not null
        references public.respuestas_encuesta(id)
        on delete cascade,

    id_pregunta uuid not null
        references public.preguntas(id)
        on delete cascade,

    respuesta_texto text,

    id_opcion uuid
        references public.opciones_pregunta(id)
        on delete set null,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint uq_respuesta_pregunta
        unique (
            id_respuesta_encuesta,
            id_pregunta
        )
);


-- ============================================================
-- 10. RESPUESTAS MÚLTIPLES
-- Para preguntas CHECKBOX
-- ============================================================

create table public.respuestas_opciones (

    id uuid primary key
        default gen_random_uuid(),

    id_respuesta uuid not null
        references public.respuestas(id)
        on delete cascade,

    id_opcion uuid not null
        references public.opciones_pregunta(id)
        on delete cascade,

    created_at timestamptz not null default now(),

    constraint uq_respuesta_opcion
        unique (
            id_respuesta,
            id_opcion
        )
);


-- ============================================================
-- 11. RECOMENDACIONES / SUGERENCIAS
-- ============================================================

create table public.recomendaciones (

    id uuid primary key
        default gen_random_uuid(),

    id_graduado uuid
        references public.graduados(id)
        on delete set null,

    mensaje text not null,

    fecha timestamptz not null default now(),

    estado varchar(30) not null default 'PENDIENTE',

    respuesta_admin text,

    id_usuario_revisor uuid
        references public.perfiles(id)
        on delete set null,

    fecha_revision timestamptz,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint chk_estado_recomendacion
        check (
            estado in (
                'PENDIENTE',
                'REVISADA',
                'ATENDIDA',
                'DESCARTADA'
            )
        )
);


-- ============================================================
-- 12. AUDITORÍA
-- ============================================================

create table public.auditoria (

    id bigint generated by default as identity primary key,

    id_usuario uuid
        references public.perfiles(id)
        on delete set null,

    accion varchar(100) not null,

    tabla_afectada varchar(100),

    id_registro varchar(100),

    descripcion text,

    ip varchar(50),

    fecha timestamptz not null default now()
);


-- ============================================================
-- 13. ÍNDICES
-- ============================================================

create index idx_perfiles_rol
on public.perfiles(id_rol);


create index idx_graduados_año_egreso
on public.graduados(año_egreso);


create index idx_graduados_año_ingreso
on public.graduados(año_ingreso);


create index idx_graduados_año_titulacion
on public.graduados(año_titulacion);


create index idx_graduados_departamento
on public.graduados(departamento);


create index idx_encuestas_estado
on public.encuestas(estado);


create index idx_encuestas_creador
on public.encuestas(id_usuario_creador);


create index idx_preguntas_encuesta
on public.preguntas(id_encuesta);


create index idx_opciones_pregunta
on public.opciones_pregunta(id_pregunta);


create index idx_respuestas_encuesta
on public.respuestas_encuesta(id_encuesta);


create index idx_respuestas_graduado
on public.respuestas_encuesta(id_graduado);


create index idx_respuestas_pregunta
on public.respuestas(id_pregunta);


create index idx_respuestas_detalle
on public.respuestas(id_respuesta_encuesta);


create index idx_respuestas_opciones_respuesta
on public.respuestas_opciones(id_respuesta);


create index idx_respuestas_opciones_opcion
on public.respuestas_opciones(id_opcion);


create index idx_recomendaciones_graduado
on public.recomendaciones(id_graduado);


create index idx_recomendaciones_estado
on public.recomendaciones(estado);


create index idx_auditoria_usuario
on public.auditoria(id_usuario);


create index idx_auditoria_fecha
on public.auditoria(fecha);


-- ============================================================
-- 14. RESTRICCIONES DE ORDEN
-- ============================================================

create unique index uq_pregunta_orden
on public.preguntas(id_encuesta, orden);


create unique index uq_opcion_orden
on public.opciones_pregunta(id_pregunta, orden);


-- ============================================================
-- 15. ROLES INICIALES
-- ============================================================

insert into public.roles
(
    nombre,
    descripcion
)
values
(
    'SUPER_ADMIN',
    'Acceso completo al sistema'
),
(
    'ADMINISTRADOR',
    'Gestión de encuestas, respuestas y reportes'
),
(
    'GRADUADO',
    'Puede actualizar sus datos y responder encuestas'
)
on conflict (nombre) do nothing;


-- ============================================================
-- 16. FUNCIÓN PARA OBTENER EL ROL DEL USUARIO
-- ============================================================

create or replace function public.obtener_rol_usuario()
returns text
language sql
security definer
stable
set search_path = public
as $$
    select r.nombre
    from public.perfiles p
    inner join public.roles r
        on r.id = p.id_rol
    where p.id = auth.uid()
    limit 1;
$$;


-- ============================================================
-- 17. FUNCIÓN PARA ACTUALIZAR updated_at
-- ============================================================

create or replace function public.actualizar_updated_at()
returns trigger
language plpgsql
as $$
begin

    new.updated_at = now();

    return new;

end;
$$;


-- ============================================================
-- 18. TRIGGERS updated_at
-- ============================================================

create trigger trg_perfiles_updated_at
before update on public.perfiles
for each row
execute function public.actualizar_updated_at();


create trigger trg_graduados_updated_at
before update on public.graduados
for each row
execute function public.actualizar_updated_at();


create trigger trg_encuestas_updated_at
before update on public.encuestas
for each row
execute function public.actualizar_updated_at();


create trigger trg_respuestas_encuesta_updated_at
before update on public.respuestas_encuesta
for each row
execute function public.actualizar_updated_at();


create trigger trg_respuestas_updated_at
before update on public.respuestas
for each row
execute function public.actualizar_updated_at();


create trigger trg_recomendaciones_updated_at
before update on public.recomendaciones
for each row
execute function public.actualizar_updated_at();


-- ============================================================
-- 19. CREAR PERFIL AUTOMÁTICAMENTE AL REGISTRAR USUARIO
-- EN SUPABASE AUTH
-- ============================================================

create or replace function public.crear_perfil_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    rol_graduado bigint;
begin

    select id
    into rol_graduado
    from public.roles
    where nombre = 'GRADUADO'
    limit 1;

    if rol_graduado is null then
        raise exception 'No existe el rol GRADUADO';
    end if;

    insert into public.perfiles
    (
        id,
        id_rol,
        nombres,
        apellidos,
        telefono
    )
    values
    (
        new.id,
        rol_graduado,
        coalesce(new.raw_user_meta_data->>'nombres', ''),
        coalesce(new.raw_user_meta_data->>'apellidos', ''),
        coalesce(new.raw_user_meta_data->>'telefono', null)
    );

    return new;

end;
$$;


create trigger trg_crear_perfil_usuario
after insert on auth.users
for each row
execute function public.crear_perfil_usuario();


-- ============================================================
-- 20. FUNCIÓN PARA AUDITORÍA
-- ============================================================

create or replace function public.registrar_auditoria()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    registro_id text;
    usuario_id uuid;
    descripcion_registro text;
begin

    usuario_id := auth.uid();

    if TG_OP = 'DELETE' then

        registro_id := coalesce(
            to_jsonb(old)->>'id',
            ''
        );

        descripcion_registro :=
            'Registro eliminado de la tabla ' || TG_TABLE_NAME;

    elsif TG_OP = 'INSERT' then

        registro_id := coalesce(
            to_jsonb(new)->>'id',
            ''
        );

        descripcion_registro :=
            'Registro creado en la tabla ' || TG_TABLE_NAME;

    else

        registro_id := coalesce(
            to_jsonb(new)->>'id',
            ''
        );

        descripcion_registro :=
            'Registro actualizado en la tabla ' || TG_TABLE_NAME;

    end if;


    insert into public.auditoria
    (
        id_usuario,
        accion,
        tabla_afectada,
        id_registro,
        descripcion
    )
    values
    (
        usuario_id,
        TG_OP,
        TG_TABLE_NAME,
        registro_id,
        descripcion_registro
    );


    if TG_OP = 'DELETE' then
        return old;
    else
        return new;
    end if;

end;
$$;


-- ============================================================
-- 21. TRIGGERS DE AUDITORÍA
-- ============================================================

create trigger trg_auditoria_perfiles
after insert or update or delete on public.perfiles
for each row
execute function public.registrar_auditoria();


create trigger trg_auditoria_graduados
after insert or update or delete on public.graduados
for each row
execute function public.registrar_auditoria();


create trigger trg_auditoria_encuestas
after insert or update or delete on public.encuestas
for each row
execute function public.registrar_auditoria();


create trigger trg_auditoria_preguntas
after insert or update or delete on public.preguntas
for each row
execute function public.registrar_auditoria();


create trigger trg_auditoria_recomendaciones
after insert or update or delete on public.recomendaciones
for each row
execute function public.registrar_auditoria();


-- ============================================================
-- 22. VALIDAR QUE UNA RESPUESTA PERTENEZCA
-- A LA ENCUESTA CORRECTA
-- ============================================================

create or replace function public.validar_respuesta_pregunta()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare

    encuesta_respuesta uuid;

    encuesta_pregunta uuid;

    estado_respuesta varchar(20);

begin

    select
        re.id_encuesta,
        re.estado
    into
        encuesta_respuesta,
        estado_respuesta
    from public.respuestas_encuesta re
    where re.id = new.id_respuesta_encuesta;


    if encuesta_respuesta is null then

        raise exception
            'La respuesta de encuesta no existe';

    end if;


    select
        p.id_encuesta
    into
        encuesta_pregunta
    from public.preguntas p
    where p.id = new.id_pregunta;


    if encuesta_pregunta is null then

        raise exception
            'La pregunta no existe';

    end if;


    if encuesta_respuesta <> encuesta_pregunta then

        raise exception
            'La pregunta no pertenece a la encuesta respondida';

    end if;


    if estado_respuesta = 'COMPLETADA' then

        raise exception
            'No se puede modificar una encuesta completada';

    end if;


    return new;

end;
$$;


create trigger trg_validar_respuesta_pregunta
before insert or update on public.respuestas
for each row
execute function public.validar_respuesta_pregunta();


-- ============================================================
-- 23. VALIDAR OPCIÓN DE RESPUESTA
-- ============================================================

create or replace function public.validar_respuesta_opcion()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare

    pregunta_respuesta uuid;

    pregunta_opcion uuid;

    estado_respuesta varchar(20);

begin

    select
        r.id_pregunta,
        re.estado
    into
        pregunta_respuesta,
        estado_respuesta
    from public.respuestas r
    inner join public.respuestas_encuesta re
        on re.id = r.id_respuesta_encuesta
    where r.id = new.id_respuesta;


    if pregunta_respuesta is null then

        raise exception
            'La respuesta no existe';

    end if;


    select
        op.id_pregunta
    into
        pregunta_opcion
    from public.opciones_pregunta op
    where op.id = new.id_opcion;


    if pregunta_opcion is null then

        raise exception
            'La opción no existe';

    end if;


    if pregunta_respuesta <> pregunta_opcion then

        raise exception
            'La opción no pertenece a la pregunta';

    end if;


    if estado_respuesta = 'COMPLETADA' then

        raise exception
            'No se puede modificar una encuesta completada';

    end if;


    return new;

end;
$$;


create trigger trg_validar_respuesta_opcion
before insert or update on public.respuestas_opciones
for each row
execute function public.validar_respuesta_opcion();


-- ============================================================
-- 24. VALIDAR COMPLETADO DE ENCUESTA
-- Verifica que todas las preguntas obligatorias tengan respuesta
-- ============================================================

create or replace function public.validar_encuesta_completada()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare

    preguntas_obligatorias integer;

    preguntas_respondidas integer;

begin

    if new.estado = 'COMPLETADA'
       and (
           old.estado is distinct from 'COMPLETADA'
       ) then

        select count(*)
        into preguntas_obligatorias
        from public.preguntas p
        where p.id_encuesta = new.id_encuesta
          and p.obligatoria = true;


        select count(distinct r.id_pregunta)
        into preguntas_respondidas
        from public.respuestas r
        inner join public.preguntas p
            on p.id = r.id_pregunta
        where r.id_respuesta_encuesta = new.id
          and p.obligatoria = true;


        if preguntas_respondidas < preguntas_obligatorias then

            raise exception
                'No se puede completar la encuesta porque faltan preguntas obligatorias';

        end if;

        new.fecha_respuesta = now();

    end if;


    return new;

end;
$$;


create trigger trg_validar_encuesta_completada
before update on public.respuestas_encuesta
for each row
execute function public.validar_encuesta_completada();


-- ============================================================
-- 25. ROW LEVEL SECURITY
-- ============================================================

alter table public.roles
enable row level security;


alter table public.perfiles
enable row level security;


alter table public.graduados
enable row level security;


alter table public.encuestas
enable row level security;


alter table public.preguntas
enable row level security;


alter table public.opciones_pregunta
enable row level security;


alter table public.respuestas_encuesta
enable row level security;


alter table public.respuestas
enable row level security;


alter table public.respuestas_opciones
enable row level security;


alter table public.recomendaciones
enable row level security;


alter table public.auditoria
enable row level security;


-- ============================================================
-- 26. POLÍTICAS: ROLES
-- ============================================================

create policy "Usuarios autenticados pueden consultar roles"
on public.roles
for select
to authenticated
using (
    true
);


-- ============================================================
-- 27. POLÍTICAS: PERFILES
-- ============================================================

create policy "Usuario puede ver su perfil"
on public.perfiles
for select
to authenticated
using (
    id = auth.uid()
    or public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


create policy "Usuario puede actualizar su perfil"
on public.perfiles
for update
to authenticated
using (
    id = auth.uid()
)
with check (
    id = auth.uid()
);


create policy "Administradores pueden gestionar perfiles"
on public.perfiles
for all
to authenticated
using (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
)
with check (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


-- ============================================================
-- 28. POLÍTICAS: GRADUADOS
-- ============================================================

create policy "Graduado puede consultar sus datos"
on public.graduados
for select
to authenticated
using (
    id = auth.uid()
    or public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


create policy "Graduado puede actualizar sus datos"
on public.graduados
for update
to authenticated
using (
    id = auth.uid()
)
with check (
    id = auth.uid()
);


create policy "Administradores pueden gestionar graduados"
on public.graduados
for all
to authenticated
using (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
)
with check (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


-- ============================================================
-- 29. POLÍTICAS: ENCUESTAS
-- ============================================================

create policy "Graduados pueden ver encuestas activas"
on public.encuestas
for select
to authenticated
using (
    (
        estado = true

        and (
            fecha_inicio is null
            or fecha_inicio <= current_date
        )

        and (
            fecha_fin is null
            or fecha_fin >= current_date
        )
    )

    or public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


create policy "Administradores pueden crear encuestas"
on public.encuestas
for insert
to authenticated
with check (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


create policy "Administradores pueden modificar encuestas"
on public.encuestas
for update
to authenticated
using (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
)
with check (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


create policy "Administradores pueden eliminar encuestas"
on public.encuestas
for delete
to authenticated
using (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


-- ============================================================
-- 30. POLÍTICAS: PREGUNTAS
-- ============================================================

create policy "Usuarios pueden consultar preguntas de encuestas activas"
on public.preguntas
for select
to authenticated
using (
    exists (
        select 1
        from public.encuestas e
        where e.id = preguntas.id_encuesta
        and (
            (
                e.estado = true

                and (
                    e.fecha_inicio is null
                    or e.fecha_inicio <= current_date
                )

                and (
                    e.fecha_fin is null
                    or e.fecha_fin >= current_date
                )
            )

            or public.obtener_rol_usuario()
                in ('SUPER_ADMIN', 'ADMINISTRADOR')
        )
    )
);


create policy "Administradores gestionan preguntas"
on public.preguntas
for all
to authenticated
using (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
)
with check (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


-- ============================================================
-- 31. POLÍTICAS: OPCIONES
-- ============================================================

create policy "Usuarios pueden consultar opciones de preguntas activas"
on public.opciones_pregunta
for select
to authenticated
using (
    exists (
        select 1
        from public.preguntas p
        inner join public.encuestas e
            on e.id = p.id_encuesta
        where p.id = opciones_pregunta.id_pregunta
        and (
            (
                e.estado = true

                and (
                    e.fecha_inicio is null
                    or e.fecha_inicio <= current_date
                )

                and (
                    e.fecha_fin is null
                    or e.fecha_fin >= current_date
                )
            )

            or public.obtener_rol_usuario()
                in ('SUPER_ADMIN', 'ADMINISTRADOR')
        )
    )
);


create policy "Administradores gestionan opciones"
on public.opciones_pregunta
for all
to authenticated
using (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
)
with check (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


-- ============================================================
-- 32. POLÍTICAS: RESPUESTAS DE ENCUESTA
-- ============================================================

create policy "Graduado puede ver sus respuestas"
on public.respuestas_encuesta
for select
to authenticated
using (
    id_graduado = auth.uid()
    or public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


create policy "Graduado puede registrar respuesta"
on public.respuestas_encuesta
for insert
to authenticated
with check (

    id_graduado = auth.uid()

    and exists (
        select 1
        from public.encuestas e
        where e.id = respuestas_encuesta.id_encuesta
        and e.estado = true
        and (
            e.fecha_inicio is null
            or e.fecha_inicio <= current_date
        )
        and (
            e.fecha_fin is null
            or e.fecha_fin >= current_date
        )
    )
);


create policy "Graduado puede actualizar borrador"
on public.respuestas_encuesta
for update
to authenticated
using (
    id_graduado = auth.uid()
    and estado = 'BORRADOR'
)
with check (
    id_graduado = auth.uid()
    and estado in ('BORRADOR', 'COMPLETADA')
);


create policy "Administradores pueden consultar respuestas"
on public.respuestas_encuesta
for select
to authenticated
using (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


-- ============================================================
-- 33. POLÍTICAS: RESPUESTAS DETALLADAS
-- ============================================================

create policy "Usuarios pueden consultar respuestas"
on public.respuestas
for select
to authenticated
using (

    exists (
        select 1
        from public.respuestas_encuesta re
        where re.id = respuestas.id_respuesta_encuesta
        and (
            re.id_graduado = auth.uid()

            or public.obtener_rol_usuario()
                in ('SUPER_ADMIN', 'ADMINISTRADOR')
        )
    )

);


create policy "Graduados pueden registrar respuestas"
on public.respuestas
for insert
to authenticated
with check (

    exists (
        select 1
        from public.respuestas_encuesta re
        where re.id = respuestas.id_respuesta_encuesta
        and re.id_graduado = auth.uid()
        and re.estado = 'BORRADOR'
    )

);


create policy "Graduados pueden actualizar respuestas"
on public.respuestas
for update
to authenticated
using (

    exists (
        select 1
        from public.respuestas_encuesta re
        where re.id = respuestas.id_respuesta_encuesta
        and re.id_graduado = auth.uid()
        and re.estado = 'BORRADOR'
    )

)
with check (

    exists (
        select 1
        from public.respuestas_encuesta re
        where re.id = respuestas.id_respuesta_encuesta
        and re.id_graduado = auth.uid()
        and re.estado = 'BORRADOR'
    )

);


create policy "Graduados pueden eliminar respuestas de borradores"
on public.respuestas
for delete
to authenticated
using (

    exists (
        select 1
        from public.respuestas_encuesta re
        where re.id = respuestas.id_respuesta_encuesta
        and re.id_graduado = auth.uid()
        and re.estado = 'BORRADOR'
    )

);


-- ============================================================
-- 34. POLÍTICAS: RESPUESTAS CHECKBOX
-- ============================================================

create policy "Usuarios pueden consultar respuestas múltiples"
on public.respuestas_opciones
for select
to authenticated
using (

    exists (
        select 1

        from public.respuestas r

        inner join public.respuestas_encuesta re
            on re.id = r.id_respuesta_encuesta

        where r.id = respuestas_opciones.id_respuesta

        and (
            re.id_graduado = auth.uid()

            or public.obtener_rol_usuario()
                in ('SUPER_ADMIN', 'ADMINISTRADOR')
        )
    )

);


create policy "Graduados pueden registrar respuestas múltiples"
on public.respuestas_opciones
for insert
to authenticated
with check (

    exists (
        select 1

        from public.respuestas r

        inner join public.respuestas_encuesta re
            on re.id = r.id_respuesta_encuesta

        where r.id = respuestas_opciones.id_respuesta

        and re.id_graduado = auth.uid()

        and re.estado = 'BORRADOR'
    )

);


create policy "Graduados pueden eliminar respuestas múltiples"
on public.respuestas_opciones
for delete
to authenticated
using (

    exists (
        select 1

        from public.respuestas r

        inner join public.respuestas_encuesta re
            on re.id = r.id_respuesta_encuesta

        where r.id = respuestas_opciones.id_respuesta

        and re.id_graduado = auth.uid()

        and re.estado = 'BORRADOR'
    )

);


-- ============================================================
-- 35. POLÍTICAS: RECOMENDACIONES
-- ============================================================

create policy "Graduado puede ver sus recomendaciones"
on public.recomendaciones
for select
to authenticated
using (
    id_graduado = auth.uid()

    or public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


create policy "Graduado puede enviar recomendaciones"
on public.recomendaciones
for insert
to authenticated
with check (
    id_graduado = auth.uid()
);


create policy "Administradores gestionan recomendaciones"
on public.recomendaciones
for update
to authenticated
using (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
)
with check (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


-- ============================================================
-- 36. POLÍTICAS: AUDITORÍA
-- ============================================================

create policy "Administradores pueden consultar auditoría"
on public.auditoria
for select
to authenticated
using (
    public.obtener_rol_usuario()
        in ('SUPER_ADMIN', 'ADMINISTRADOR')
);


-- ============================================================
-- 37. COMENTARIOS DESCRIPTIVOS
-- ============================================================

comment on table public.roles is
'Roles de acceso al sistema de seguimiento a graduados';


comment on table public.perfiles is
'Información básica de los usuarios autenticados mediante Supabase Auth';


comment on table public.graduados is
'Información académica, personal y profesional básica de los graduados';


comment on table public.encuestas is
'Encuestas utilizadas para realizar seguimiento a los graduados';


comment on table public.preguntas is
'Preguntas dinámicas pertenecientes a las encuestas';


comment on table public.opciones_pregunta is
'Opciones disponibles para preguntas de selección';


comment on table public.respuestas_encuesta is
'Registro de participación de un graduado en una encuesta';


comment on table public.respuestas is
'Respuestas individuales de las preguntas';


comment on table public.respuestas_opciones is
'Opciones seleccionadas en preguntas de tipo CHECKBOX';


comment on table public.recomendaciones is
'Sugerencias y comentarios enviados por los graduados';


comment on table public.auditoria is
'Registro de operaciones importantes realizadas en el sistema';


-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================