name: proyecto_final_360
description: Base academica generica y adaptable para el Trabajo Final del Diplomado UAJMS.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ">=6.1.2 <7.0.0"
  shared_preferences: ">=2.3.3 <3.0.0"
  supabase_flutter: ">=2.15.4 <3.0.0"
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <7.0.0"
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
